### ISSUE TITLE
unresolved import `lunatic::net`

### ISSUE THREAD

**Issue by ArneVogel** [lunatic-lang/lunatic#11]
Hi,

I was trying out the networking example from [this](https://dev.to/bkolobara/writing-rust-the-elixir-way-2lm8) blog post and encountered this error:
```
error[E0432]: unresolved import `lunatic::net`
 --> src/main.rs:1:24
  |
1 | use lunatic::{Process, net}; // Once WASI gets networking support you will be able to use Rust's `std::net::TcpStream` instead.
  |                        ^^^ no `net` in the root
```

Cargo.toml:
```
[dependencies]
lunatic = "0.2.0"
```
Building with `cargo build --release --target=wasm32-wasi`

Thanks,
Arne

**Comment by bkolobara** [comment]
Hi @ArneVogel! Thank you for reporting this.

The issue is that I used the source code directly as a dependency for the blog post instead of `lunatic = "0.2.0"`.
I have a published the `0.2.1` release containing the latest source, it should work now.
