### ISSUE TITLE
The Discord invite has expired

### ISSUE THREAD

**Issue by teymour-aldridge** [lunatic-lang/lunatic#6]

**Comment by bkolobara** [comment]
Thanks @teymour-aldridge for letting me know. You can use this link: https://discord.gg/tRfnMPSG27. I have also updated the readme file.

**Comment by obmarg** [comment]
@bkolobara this new discord link appears to be for a warcraft server:

<img width="393" alt="image" src="https://user-images.githubusercontent.com/556490/100081862-69561a80-2e3f-11eb-90d4-237286fd0c88.png">

**Comment by bkolobara** [comment]
@obmarg Thanks for letting me know. I accidentally copied the wrong invite. This is the correct one: https://discord.gg/b7zDqpXpB4
I have also fixed the readme, let me know if there is maybe another place I left the old link.
